### ISSUE TITLE
大神，有些帖子转不了

### ISSUE THREAD

**Issue by JokeJoe8806** [lexdene/tieba-post-to-epub#8]
比如这个 https://tieba.baidu.com/p/6067155134

**Comment by lexdene** [comment]
放假期间好懒呀……
不想修 bug ……

**Comment by JokeJoe8806** [comment]
base.py文件改成 text = await resp.text(errors="ignore")。就是多那个参数应该就行了
我python很菜，只会写单文件脚本

2019-05-02 

dg8806 



发件人：刘项 <notifications@github.com>
发送时间：2019-05-02 18:30
主题：Re: [lexdene/tieba-post-to-epub] 大神，有些帖子转不了 (#8)
收件人："lexdene/tieba-post-to-epub"<tieba-post-to-epub@noreply.github.com>
抄送："JokeJoe8806"<dg8806@163.com>,"Author"<author@noreply.github.com>

放假期间好懒呀……
不想修 bug ……
